-- -----------------------  EDUCATIONAL ANALYSIS  ------------------------


-- Q11-  educational attainment of professional developers? ----------------------------

SELECT EdLevel , COUNT(EdLevel) AS COUNT, COUNT(EdLevel)*100/SUM(COUNT(EdLevel))
-- IF WE DON'T USE OVER() HERE, SUM(COUNT(EdLevel)) WILL DO COUNT OF OCCURANCES OF
-- EACH SPECIFIC CATEGPRY OF EDLEVEL AND THERE SUM WOULD ALSO BE THE SAME VALUE, AND
-- AS A RESULT, YOU GOT 100% IN EACH EDLEVEL CATEGORY 
 OVER () AS PERCENTAGE FROM survey_results_2024 WHERE 
MainBranch = 'I am a developer by profession' AND 
EDLEVEL IS NOT NULL AND EDLEVEL !='NA'
 GROUP BY EDLEVEL ORDER BY COUNT DESC;

-- Q12- how survey respondents learn to code based on their age?  -----------------------------


WITH RECURSIVE LEARNING_PLATFORMS AS (
  SELECT 
    AGE, 
    SUBSTRING_INDEX(LEARNCODE, ';', 1) AS PLATFORM,
    CASE 
      WHEN LOCATE(';', LEARNCODE) > 0 THEN SUBSTRING(LEARNCODE, LOCATE(';', LEARNCODE) + 1)
      ELSE '' 
    END AS REM
  FROM survey_results_2024

  UNION ALL

  SELECT 
    AGE, 
    SUBSTRING_INDEX(REM, ';', 1) AS PLATFORM,
    CASE 
      WHEN LOCATE(';', REM) > 0 THEN SUBSTRING(REM, LOCATE(';', REM) + 1)
      ELSE '' 
    END AS REM
  FROM LEARNING_PLATFORMS
  WHERE REM IS NOT NULL AND REM != ''
)

SELECT 
  PLATFORM, 
  COUNT(PLATFORM) * 100.0 / SUM(COUNT(PLATFORM)) OVER() AS total_percentage,

  -- Age group percentages
  ROUND(SUM(CASE WHEN age = 'Under 18 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = 'Under 18 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_under_18,

  ROUND(SUM(CASE WHEN age = '18-24 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '18-24 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_18_24,

  ROUND(SUM(CASE WHEN age = '25-34 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '25-34 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_25_34,

  ROUND(SUM(CASE WHEN age = '35-44 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '35-44 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_35_44,

  ROUND(SUM(CASE WHEN age = '45-54 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '45-54 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_45_54,

  ROUND(SUM(CASE WHEN age = '55-64 years old' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '55-64 years old' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_55_64,

  ROUND(SUM(CASE WHEN age = '65 years or older' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = '65 years or older' THEN 1 ELSE 0 END)) OVER(),2) AS percentage_65_plus,

  ROUND(SUM(CASE WHEN age = 'Prefer not to say' THEN 1 ELSE 0 END) * 100.0
    / SUM(SUM(CASE WHEN age = 'Prefer not to say' THEN 1 ELSE 0 END)) OVER(), 2) AS percentage_prefer_not_to_say

FROM LEARNING_PLATFORMS
WHERE PLATFORM IS NOT NULL AND PLATFORM != 'NA'
GROUP BY PLATFORM
ORDER BY total_percentage DESC;

-- &&&&&&&&&&&&&&&&&&     2ND WAY TO DO THIS   &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
WITH RECURSIVE LEARNING_PLATFORMS AS (
  SELECT 
    AGE, 
    SUBSTRING_INDEX(LEARNCODE, ';', 1) AS PLATFORM,
    CASE 
      WHEN LOCATE(';', LEARNCODE) > 0 THEN SUBSTRING(LEARNCODE, LOCATE(';', LEARNCODE) + 1)
      ELSE '' 
    END AS REM
  FROM survey_results_2024

  UNION ALL

  SELECT 
    AGE, 
    SUBSTRING_INDEX(REM, ';', 1) AS PLATFORM,
    CASE 
      WHEN LOCATE(';', REM) > 0 THEN SUBSTRING(REM, LOCATE(';', REM) + 1)
      ELSE '' 
    END AS REM
  FROM LEARNING_PLATFORMS
  WHERE REM IS NOT NULL AND REM != ''
)

SELECT 
  PLATFORM, AGE, 
  COUNT(PLATFORM) * 100.0 / SUM(COUNT(PLATFORM)) OVER(PARTITION BY AGE) AS total_percentage

  -- Age group percentages
  
FROM LEARNING_PLATFORMS
WHERE PLATFORM IS NOT NULL AND PLATFORM != 'NA'
GROUP BY PLATFORM,AGE
ORDER BY AGE, total_percentage;


-- Q12 - Top 10 online resources for learning code? -------------------------------
WITH RECURSIVE ONLINE_RESOURCES AS (
  SELECT 
    AGE, 
    SUBSTRING_INDEX(LEARNCODEONLINE, ';', 1) AS ONLINE_RESOURCE,
    CASE 
      WHEN LOCATE(';', LEARNCODEONLINE) > 0 THEN SUBSTRING(LEARNCODEONLINE, LOCATE(';', LEARNCODEONLINE) + 1)
      ELSE '' 
    END AS REM
  FROM survey_results_2024

  UNION ALL

  SELECT 
    AGE, 
    SUBSTRING_INDEX(REM, ';', 1) AS ONLINE_RESOURCE,
    CASE 
      WHEN LOCATE(';', REM) > 0 THEN SUBSTRING(REM, LOCATE(';', REM) + 1)
      ELSE '' 
    END AS REM
  FROM ONLINE_RESOURCES
  WHERE REM IS NOT NULL AND REM != ''
)

SELECT 
  ONLINE_RESOURCE, 
ROUND(COUNT(ONLINE_RESOURCE)*100/SUM(COUNT(ONLINE_RESOURCE)) OVER(),2) AS RESOURCE_PERCENTAGE FROM ONLINE_RESOURCES
GROUP BY ONLINE_RESOURCE ORDER BY RESOURCE_PERCENTAGE DESC;


-- Q13- How many years have developers been coding, both overall and professionally?  --------------------------


WITH OVERALL_YEARS_OF_CODE AS(
SELECT RESPONSEID,
  CASE 
    WHEN YearsCode = 'Less than 1 year' THEN 'Less than 1 year'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 1 AND 4 THEN '1 to 4 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 5 AND 9 THEN '5 to 9 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 10 AND 14 THEN '10 to 14 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 15 AND 19 THEN '15 to 19 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 20 AND 24 THEN '20 to 24 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 25 AND 29 THEN '25 to 29 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 30 AND 34 THEN '30 to 34 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 35 AND 39 THEN '35 to 39 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 40 AND 44 THEN '40 to 44 years'
    WHEN CAST(YearsCode AS UNSIGNED) BETWEEN 45 AND 49 THEN '45 to 49 years'
    WHEN YearsCode = 'More than 50 years' THEN 'More than 50 years'
    ELSE 'Unknown'
  END AS OVERALL_CODING_YEARS FROM survey_results_2024)

  SELECT OVERALL_CODING_YEARS AS OVERALL_EXPERIENCE, 
  
  ROUND(COUNT(OVERALL_CODING_YEARS)*100/SUM(COUNT(OVERALL_CODING_YEARS)) OVER(),2) 
  AS OVERALL_CODING_YEARS_PERCENT
  FROM OVERALL_YEARS_OF_CODE
 WHERE OVERALL_CODING_YEARS IS NOT NULL AND 
 OVERALL_CODING_YEARS!='NA' AND OVERALL_CODING_YEARS!='UNKNOWN' 
  GROUP BY OVERALL_CODING_YEARS ORDER BY OVERALL_EXPERIENCE;
 
 -- ------------ PROFESSIONAL CODING EXPERINECE: --------------
 
 
  WITH PROFESSIONAL_CODING_YEARS AS(
  SELECT RESPONSEID,
  CASE 
    WHEN YearsCodePRO = 'Less than 1 year' THEN 'Less than 1 year'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 1 AND 4 THEN '1 to 4 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 5 AND 9 THEN '5 to 9 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 10 AND 14 THEN '10 to 14 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 15 AND 19 THEN '15 to 19 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 20 AND 24 THEN '20 to 24 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 25 AND 29 THEN '25 to 29 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 30 AND 34 THEN '30 to 34 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 35 AND 39 THEN '35 to 39 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 40 AND 44 THEN '40 to 44 years'
    WHEN CAST(YearsCodePRO AS UNSIGNED) BETWEEN 45 AND 49 THEN '45 to 49 years'
    WHEN YearsCodePRO = 'More than 50 years' THEN 'More than 50 years'
    ELSE 'Unknown'
  END AS PROF_CODING_YEARS FROM survey_results_2024
  )
  
SELECT  
PROF_CODING_YEARS AS PROFESSIONAL_EXPERIENCE,
ROUND(COUNT(PROF_CODING_YEARS)*100/SUM(
COUNT(PROF_CODING_YEARS)) OVER(),2) AS PROF_CODING_YEARS_PERCENT
FROM PROFESSIONAL_CODING_YEARS 
WHERE  PROF_CODING_YEARS IS NOT NULL AND PROF_CODING_YEARS!='NA'
AND PROF_CODING_YEARS!='UNKNOWN' GROUP BY  PROF_CODING_YEARS
ORDER BY PROF_CODING_YEARS;
 

-- Q14- What TYPE OF developers have more than 15 years of coding experience?    --------------------------------

SELECT 
    DEVTYPE, ROUND(AVG(YearsCodePRO), 2) AS EXPERIENCE
FROM
    survey_results_2024
WHERE
    DEVTYPE != 'NA' AND YearsCodePRO != 'NA'
    GROUP BY DEVTYPE
	HAVING EXPERIENCE>15
ORDER BY EXPERIENCE DESC;


-- -----------------------------   TECHNICAL ANALYSIS ---------------------------
-- Q15- What are top 5 popular languages used by people who are learning to code?  -----------------------------------

WITH RECURSIVE LANGUAGE_USED AS(
SELECT MAINBRANCH, SUBSTRING_INDEX(LanguageHaveWorkedWith, ';',1) AS LANG,

CASE WHEN (LOCATE(';', LanguageHaveWorkedWith)>1) THEN 
SUBSTRING(LanguageHaveWorkedWith, LOCATE(';',LanguageHaveWorkedWith)+1) 
ELSE '' END AS REM FROM survey_results_2024

UNION ALL
 
SELECT MAINBRANCH, SUBSTRING_INDEX(REM, ';',1) AS LANG,

CASE WHEN (LOCATE(';', REM)>1) THEN 
SUBSTRING(REM, LOCATE(';',REM)+1) 
ELSE '' END AS REM FROM LANGUAGE_USED
WHERE REM !='NA' AND REM IS NOT NULL AND REM!='')

SELECT LANG, COUNT(LANG)*100/SUM(COUNT(LANG)) OVER() AS COUNT FROM LANGUAGE_USED WHERE MAINBRANCH 
LIKE '%LEARNING TO CODE%' GROUP BY LANG ORDER BY COUNT DESC LIMIT 5;


-- Q16- top 3 most common IDEs used by professional developers?  -------------------------------
WITH RECURSIVE PLATFORM AS(
SELECT MAINBRANCH, SUBSTRING_INDEX(NEWCollabToolsHaveWorkedWith, ';',1) AS IDE,

CASE WHEN (LOCATE(';', NEWCollabToolsHaveWorkedWith)>1) THEN 
SUBSTRING(PlatformHaveWorkedWith, LOCATE(';',NEWCollabToolsHaveWorkedWith)+1) 
ELSE '' END AS REM FROM survey_results_2024

UNION ALL
 
SELECT MAINBRANCH, SUBSTRING_INDEX(REM, ';',1) AS LANG,

CASE WHEN (LOCATE(';', REM)>1) THEN 
SUBSTRING(REM, LOCATE(';',REM)+1) 
ELSE '' END AS REM FROM PLATFORM
WHERE REM !='NA' AND REM IS NOT NULL AND REM!='')

SELECT IDE, ROUND(COUNT(IDE)*100/SUM(COUNT(IDE)) OVER(),2) AS TOP_IDEs FROM 
PLATFORM where IDE is not null and IDE !='NA' GROUP BY IDE ORDER BY TOP_IDEs
desc limit 3 ;

-- Q17- What are the most commonly used operating systems by developers 
-- for personal and professional use? ------------------------

-- `OpSysPersonal use` 
-- `OpSysProfessional use`

WITH RECURSIVE OSPERSONAL AS(
SELECT SUBSTRING_INDEX(`OpSysPersonal use`, ';',1) AS OS,
CASE WHEN (LOCATE(';', `OpSysPersonal use`)>1) THEN 
SUBSTRING(`OpSysPersonal use`, LOCATE(';',`OpSysPersonal use`)+1) 
ELSE '' END AS REM FROM survey_results_2024

		UNION ALL
 
SELECT SUBSTRING_INDEX(REM, ';',1) AS OS,
CASE WHEN (LOCATE(';', REM)>1) THEN 
SUBSTRING(REM, LOCATE(';',REM)+1) 
ELSE '' END AS REM FROM OSPERSONAL
WHERE REM !='NA' AND REM IS NOT NULL AND REM!=''),

OSPROFESSIONAL AS (
SELECT SUBSTRING_INDEX(`OpSysProfessional use`, ';',1) AS OS,
CASE WHEN (LOCATE(';', `OpSysProfessional use`)>1) THEN 
SUBSTRING(`OpSysProfessional use`, LOCATE(';',`OpSysProfessional use`)+1) 
ELSE '' END AS REM FROM survey_results_2024

		UNION ALL
 
SELECT SUBSTRING_INDEX(REM, ';',1) AS OS,
CASE WHEN (LOCATE(';', REM)>1) THEN 
SUBSTRING(REM, LOCATE(';',REM)+1) 
ELSE '' END AS REM FROM OSPROFESSIONAL
WHERE REM !='NA' AND REM IS NOT NULL AND REM!=''),

OSPERS_COUNT AS (
SELECT OS, ROUND(COUNT(OS)*100/SUM(COUNT(OS)) OVER(),2) AS 
PERSONAL_USE_PERCENT FROM OSPERSONAL WHERE OS IS NOT NULL AND OS !='NA' 
GROUP BY 
OS ),
OSPROF_COUNT AS (
SELECT  OS, ROUND(COUNT(OS)*100/SUM(COUNT(OS)) OVER(),2) AS 
PROFESSIONAL_USE_PERCENT FROM OSPROFESSIONAL WHERE OS IS NOT NULL AND OS !='NA'
 GROUP BY OS
)

SELECT OSPERS_COUNT.OS, OSPERS_COUNT.PERSONAL_USE_PERCENT , 
OSPROF_COUNT.PROFESSIONAL_USE_PERCENT
FROM OSPERS_COUNT LEFT JOIN OSPROF_COUNT ON
OSPERS_COUNT.OS = OSPROF_COUNT.OS 
UNION 
SELECT OSPERS_COUNT.PERSONAL_USE_PERCENT, OSPROF_COUNT.OS, OSPROF_COUNT.PROFESSIONAL_USE_PERCENT
FROM OSPROF_COUNT RIGHT JOIN OSPERS_COUNT ON 
OSPROF_COUNT.OS = OSPERS_COUNT.OS WHERE 
OSPROF_COUNT.PROFESSIONAL_USE_PERCENT IS NULL 
ORDER BY PERSONAL_USE_PERCENT DESC; 

-- ------------------------  WORK BASED ANALYSIS -----------------------

-- Q18- EMPLOYMENT STATUS BY GEOGRAPHY?
WITH RECURSIVE emp AS(
SELECT COUNTRY, SUBSTRING_INDEX(EMPLOYMENT, ';',1) AS employ,
CASE WHEN (LOCATE(';', EMPLOYMENT)>1) THEN 
SUBSTRING(EMPLOYMENT, LOCATE(';',EMPLOYMENT)+1) 
ELSE '' END AS REM FROM survey_results_2024

		UNION ALL

SELECT COUNTRY, SUBSTRING_INDEX(REM, ';',1) AS EMPLOY,
CASE WHEN (LOCATE(';', REM)>1) THEN 
SUBSTRING(REM, LOCATE(';',REM)+1) 
ELSE '' END AS REM FROM emp
WHERE REM !='NA' AND REM IS NOT NULL AND REM!='')

SELECT COUNTRY, EMPLOY,
 ROUND(COUNT(EMPLOY)*100/SUM(COUNT(EMPLOY)) OVER(PARTITION BY COUNTRY),2)
AS DEVELOPER_PERCENTAGE
FROM EMP 
GROUP BY COUNTRY,EMPLOY ORDER BY COUNTRY,DEVELOPER_PERCENTAGE DESC ;

-- Q19- NUMBER OF EMPLOYES IN ORGANIZATION IN WHICH PEOPLE WORK?   ------------------------------

SELECT OrgSize, COUNT(OrgSize)*100/SUM(COUNT(ORGSIZE)) OVER() 
AS PERCENTAGE_COUNT FROM survey_results_2024
WHERE OrgSize!='NA' AND ORGSIZE IS NOT NULL GROUP BY ORGSIZE
ORDER BY PERCENTAGE_COUNT DESC;

